### ISSUE TITLE
The version of the repository is inconsistent with the version on the pub

### ISSUE THREAD

**Issue by januwA** [codeanticode/p5.dart#2]
Pub:
![image](https://user-images.githubusercontent.com/22570563/64916074-75a90700-d7a8-11e9-8b89-794a28baebc8.png)

Github:
![image](https://user-images.githubusercontent.com/22570563/64916078-848fb980-d7a8-11e9-97c0-4d341f236d81.png)

Please update the source version of the repository 🔥

**Comment by codeanticode** [comment]
Thanks for noting this discrepancy, fixed with https://github.com/codeanticode/p5.dart/commit/02f420343cfbda283644d3be72a599ec70c2fdcc
