### ISSUE TITLE
can use p5 audio tools ?

### ISSUE THREAD

**Issue by odaymusic** [codeanticode/p5.dart#6]
can use p5 audio tools ?

**Comment by codeanticode** [comment]
Not sure, I think the main hurdle is that p5 libraries are written in Java, a different language from Dart. Some information in this reddit thread could be useful:

https://www.reddit.com/r/dartlang/comments/i6j0bi/can_i_add_a_jar_library_to_dart_and_flutter/

**Comment by aalex** [comment]
In short: no.

**Comment by codeanticode** [comment]
Duplicate of #3
